### ISSUE TITLE
Add delicious Sodexo restaurants to the list

### ISSUE THREAD

**Issue by petetnt** [sirtawast/helsinkilunch_old#2]
They have a JSON API
https://www.sodexo.fi/ruokalistat/output/daily_json/49/2018/03/15/fi

**Comment by sirtawast** [comment]
Wholly GRAB. I'm aware but was lazy 🕶 🌞

**Comment by sirtawast** [comment]
Are you sure you want that stuff in? This is bremium gold medal food service 🥇

**Comment by petetnt** [comment]
pls implement

**Comment by sirtawast** [comment]
@petetnt Any :octocat: contributions  are welcome 👍

**Comment by petetnt** [comment]
lezy developar!!!
